### ISSUE TITLE
"Youth fountain" gene ages up "youth sex" partners 

### ISSUE THREAD

**Issue by Stretop** [vegapnk/RJW-Genes#28] opened 2023-03-29 01:40 UTC
Steps to reproduce:
1) Allow "youth sex" in RJW mod settings.
2) Have a humanlike pawn with a "Youth fountain" gene.
3) Have another humanlike pawn 16 to 19 years old.
4) Engage those two pawns in loving'

Expected result:
_Ether_
The younger pawn retains its age.
_Or_
The younger pawn get younger till the age of 16.

Actual result:
The younger pawn's age is set to 20.

**Comment by vegapnk** [comment] 2023-03-30 07:24
Duplicate of #26 , 

I will think a bit about it.

**Comment by Stretop** [comment] 2023-03-30 23:33
I just feel compelled to mention that this is not about any kind of degeneracy, but rather about "biological age economy" stemming from using Timeskip card psycasts from Vanilla Psycasts Expanded.

Without going into too much detail: there biological age is gained and spent as a resource for psycasts, and thus such sudden aging is somewhat disruptive.

**Comment by vegapnk** [comment] 2023-03-31 15:43
Feel free to go into detail 🤔  

I am not sure, does it enable people to have sex before 18? 

I think what I maybe do is to cap it at ~20 again and age can only go downward, but I am not sure. I'd not like to account for 250 Corner Cases (no matter how degenerate or not they are)

**Closed** 2023-04-06 06:32 UTC
Labels: Duplicate
